spring.application.name=TrackTheRun

spring.datasource.driver-class-name=org.postgresql.Driver

# DI - Docker variables


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true